# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  web:
    image: web
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 5261:5261
