# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - purple

  web:
    image: web
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - configuration=Debug
      network: host
    ports:
      - 5261:5261
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PurpleConnection="Host=db;Port=5432;Database=${DATABASE_NAME};User Id=postgres;Password=${POSTGRES_PASSWORD};"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    networks:
      - purple

networks:
  purple:
    name: purple
    driver: bridge
